### ISSUE TITLE
Could not run your program

### ISSUE THREAD

**Issue by JafferWilson** [arun-mansa/tradingbot#6]
```
C:\Python35\python.exe C:/Users/AIMS/Desktop/tradingbot-master/starter.py
Traceback (most recent call last):
  File "C:/Users/AIMS/Desktop/tradingbot-master/starter.py", line 10, in <module>
    from signaler import create_signaler
  File "C:\Users\AIMS\Desktop\tradingbot-master\signaler.py", line 5, in <module>
    import patterns.constants as pattern_constants
  File "C:\Users\AIMS\Desktop\tradingbot-master\patterns\constants.py", line 3, in <module>
    from test import TEST
ImportError: cannot import name 'TEST'

Process finished with exit code 1
```
Above is what I am getting after running the starter.py file. please help.

**Comment by tahmi123** [comment]
Run on python 2.7

**Comment by JafferWilson** [comment]
What are the indicators you are using in this bot?

**Comment by tahmi123** [comment]
rsi, aroonup and down, bollingerband, stoch.

**Comment by JafferWilson** [comment]
Thank you for your help.
